"""initial schema

Revision ID: e1b389192dff
Revises: 
Create Date: 2026-08-23 15:36:19.065280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1b389192dff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_allocation_key', sa.Enum('WF', 'NF', 'CONSUMPTION', 'NONE', name='allocation_key_enum', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('street', sa.String(length=200), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allocation_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('cost_category_id', sa.Integer(), nullable=False),
    sa.Column('allocation_key', sa.Enum('WF', 'NF', 'CONSUMPTION', 'NONE', name='allocation_key_enum', native_enum=False, length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cost_category_id'], ['cost_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'cost_category_id', name='uq_allocation_property_category')
    )
    op.create_index(op.f('ix_allocation_configs_cost_category_id'), 'allocation_configs', ['cost_category_id'], unique=False)
    op.create_index(op.f('ix_allocation_configs_property_id'), 'allocation_configs', ['property_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('cost_category_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['cost_category_id'], ['cost_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_cost_category_id'), 'invoices', ['cost_category_id'], unique=False)
    op.create_index(op.f('ix_invoices_property_id'), 'invoices', ['property_id'], unique=False)
    op.create_table('lease_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=False),
    sa.Column('living_area', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('extra_area', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lease_units_property_id'), 'lease_units', ['property_id'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'FINAL', name='settlement_status_enum', native_enum=False, length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'year', name='uq_settlement_property_year')
    )
    op.create_index(op.f('ix_settlements_property_id'), 'settlements', ['property_id'], unique=False)
    op.create_table('techem_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('GAS', 'HEATING_ELECTRICITY', name='techem_kind_enum', native_enum=False, length=30), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('quantity_kwh', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_techem_records_property_id'), 'techem_records', ['property_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_table('meters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('lease_unit_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('meter_type', sa.Enum('APARTMENT_WATER', 'WASHING_MACHINE', 'GARDEN', 'HEATING_ELECTRICITY', 'GAS', 'ELECTRICITY', 'OTHER', name='meter_type_enum', native_enum=False, length=30), nullable=False),
    sa.Column('unit', sa.Enum('M3', 'KWH', name='meter_unit_enum', native_enum=False, length=10), nullable=False),
    sa.ForeignKeyConstraint(['lease_unit_id'], ['lease_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meters_lease_unit_id'), 'meters', ['lease_unit_id'], unique=False)
    op.create_index(op.f('ix_meters_property_id'), 'meters', ['property_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lease_unit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('move_in', sa.Date(), nullable=False),
    sa.Column('move_out', sa.Date(), nullable=True),
    sa.Column('monthly_advance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['lease_unit_id'], ['lease_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_lease_unit_id'), 'tenants', ['lease_unit_id'], unique=False)
    op.create_table('meter_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meter_id', 'reading_date', name='uq_meter_reading')
    )
    op.create_index(op.f('ix_meter_readings_meter_id'), 'meter_readings', ['meter_id'], unique=False)
    op.create_table('settlement_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settlement_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('total_costs', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('advance_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_lines_settlement_id'), 'settlement_lines', ['settlement_id'], unique=False)
    op.create_index(op.f('ix_settlement_lines_tenant_id'), 'settlement_lines', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settlement_lines_tenant_id'), table_name='settlement_lines')
    op.drop_index(op.f('ix_settlement_lines_settlement_id'), table_name='settlement_lines')
    op.drop_table('settlement_lines')
    op.drop_index(op.f('ix_meter_readings_meter_id'), table_name='meter_readings')
    op.drop_table('meter_readings')
    op.drop_index(op.f('ix_tenants_lease_unit_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_meters_property_id'), table_name='meters')
    op.drop_index(op.f('ix_meters_lease_unit_id'), table_name='meters')
    op.drop_table('meters')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_techem_records_property_id'), table_name='techem_records')
    op.drop_table('techem_records')
    op.drop_index(op.f('ix_settlements_property_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_lease_units_property_id'), table_name='lease_units')
    op.drop_table('lease_units')
    op.drop_index(op.f('ix_invoices_property_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_cost_category_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_allocation_configs_property_id'), table_name='allocation_configs')
    op.drop_index(op.f('ix_allocation_configs_cost_category_id'), table_name='allocation_configs')
    op.drop_table('allocation_configs')
    op.drop_table('properties')
    op.drop_table('cost_categories')
    # ### end Alembic commands ###
